### ISSUE TITLE
Reduce operations raise error for negative axis values

### ISSUE THREAD

**Issue by nils-werner** [pydata/sparse#117]
Reduce operations like `.sum()`, `.prod()` etc. raise exceptions when you pass a negative `axis` value:

```python
import sparse
sparse.random((40, 50)).sum(0)  # works
sparse.random((40, 50)).sum(1)  # works
sparse.random((40, 50)).sum(-1)  # fails, should be equivalent to .sum(1)
```

The traceback I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "proj_dir/sparse/sparse/coo.py", line 1038, in prod
    return self.reduce(np.multiply, axis=axis, keepdims=keepdims, dtype=dtype)
  File "proj_dir/sparse/sparse/coo.py", line 771, in reduce
    a = self.transpose(neg_axis + axis)
  File "proj_dir/sparse/sparse/coo.py", line 1099, in transpose
    raise ValueError("repeated axis in transpose")
ValueError: repeated axis in transpose
```

**Comment by hameerabbasi** [comment]
@nils-werner Are you interested in fixing this? It's trivial. You just need to flip the axes to be positive near the top of `COO.reduce`.

**Comment by nils-werner** [comment]
Yeah, I can do that.
