### ISSUE TITLE
Cryptic error message during densification of array when doing elemwise computation.

### ISSUE THREAD

**Issue by asmeurer** [pydata/sparse#230]
```py
>>> X = np.arange(24)
>>> zeros = sparse.zeros(X.shape)
>>> ones = sparse.ones(X.shape)
>>> sparse.where(X < 6, zeros, ones)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sparse/coo/common.py", line 777, in where
    return elemwise(np.where, condition, x, y)
  File "./sparse/coo/umath.py", line 47, in elemwise
    return _Elemwise(func, *args, **kwargs).get_result()
  File "./sparse/coo/umath.py", line 422, in __init__
    self._get_fill_value()
  File "./sparse/coo/umath.py", line 484, in _get_fill_value
    raise ValueError('Inconsistent fill-values in the result array: operating on the ndarray with'
ValueError: Inconsistent fill-values in the result array: operating on the ndarray with fill-values produces inconsistent results.
```

It works if the input array is sparse.

```py
>>> sparse.where(sparse.COO.from_numpy(X) < 6, zeros, ones)
<COO: shape=(24,), dtype=float64, nnz=18, fill_value=0.0>
```

**Comment by hameerabbasi** [comment]
This is as desired. The rule for any element-wise function is: `func(ndarrays, sparse_fill_values)` should be a constant array.

**Comment by asmeurer** [comment]
I don't know if this is related. Any idea why this isn't working? I think it used to work.

```
>>> author_factor
<COO: shape=(2862, 5), dtype=float64, nnz=14310, fill_value=0.0>
>>> np.where(np.abs(author_factor) < 0.005, np.nan, author_factor)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-40-6ddd6a1e4b9f> in <module>
----> 1 np.where(np.abs(author_factor) < 0.005, np.nan, author_factor)

~/anaconda3/lib/python3.6/site-packages/sparse/sparse_array.py in __array__(self, **kwargs)
    211         from . import _AUTO_DENSIFICATION_ENABLED as densify
    212         if not densify:
--> 213             raise RuntimeError('Cannot convert a sparse array to dense automatically. '
    214                                'To manually densify, use the todense method.')
    215 

RuntimeError: Cannot convert a sparse array to dense automatically. To manually densify, use the todense method.
```

As far as I can tell it should be able to compute the `where` sparsely using `nan` as a fill value.

**Comment by hameerabbasi** [comment]
This second one works fine for me.

```python
import numpy as np
import sparse

x = sparse.random((10, 10))

y = (np.abs(x) < 0.2)
r = sparse.where(y, np.nan, x)
```

It runs without exceptions.

**Comment by asmeurer** [comment]
The problem occurs with `np.where`, not `sparse.where`.

**Comment by hameerabbasi** [comment]
Ah, yes. Currently, the way to override `np.where` is `__array_function__`, which we haven’t done. Although `np.where` is ufunc-like, and there are plans to make it into one, it isn’t one yet.

There was no support for `np.where` at any point in time.
