### ISSUE TITLE
IndexError on different shape arrays when computing ufunc

### ISSUE THREAD

**Issue by pentschev** [pydata/sparse#242]
I have identified the following behavior during https://github.com/dask/dask/pull/4525:

```python
(Pdb) p divide(totals, ns, dtype=dtype)
<COO: shape=(2, 2, 2), dtype=float64, nnz=6, fill_value=0.0>
(Pdb) mu
<COO: shape=(1, 1, 1), dtype=float64, nnz=1, fill_value=0.0>
(Pdb) p divide(totals, ns, dtype=dtype) - mu
*** IndexError: index 1 is out of bounds for axis 0 with size 1
```

I'm not sure what's the expected behavior in such situation for sparse arrays, but a subtraction of arrays in shape (2,2,2) and (1,1,1) works with NumPy arrays, would you say this is a bug @hameerabbasi ?

A snippet to reproduce an traceback follow:

```python
import numpy as np
import sparse

a = sparse.COO.from_numpy(np.ones((2, 2, 2)))
b = sparse.COO.from_numpy(np.ones((1, 1, 1)))

a - b
```

```python
Traceback (most recent call last):
  File "sparse_indexerror.py", line 7, in <module>
    a - b
  File "/home/pentschev/.local/lib/python3.5/site-packages/numpy/lib/mixins.py", line 25, in func
    return ufunc(self, other)
  File "/home/pentschev/.local/lib/python3.5/site-packages/sparse/coo/core.py", line 1454, in __array_ufunc__
    result = elemwise(ufunc, *inputs, **kwargs)
  File "/home/pentschev/.local/lib/python3.5/site-packages/sparse/coo/umath.py", line 48, in elemwise
    return _Elemwise(func, *args, **kwargs).get_result()
  File "/home/pentschev/.local/lib/python3.5/site-packages/sparse/coo/umath.py", line 444, in get_result
    r = self._get_func_coords_data(mask)
  File "/home/pentschev/.local/lib/python3.5/site-packages/sparse/coo/umath.py", line 579, in _get_func_coords_data
    func_coords, func_data = _get_expanded_coords_data(func_coords, func_data, params, self.shape)
  File "/home/pentschev/.local/lib/python3.5/site-packages/sparse/coo/umath.py", line 263, in _get_expanded_coords_data
    expanded_data = data[all_idx[first_dim]]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by hameerabbasi** [comment]
It seems like broadcasting isn’t working properly...
