### ISSUE TITLE
Sparse does not install on Python 3.9.1 due to numba llvmlite dependency issue 

### ISSUE THREAD

**Issue by JackWetherell** [pydata/sparse#426]
**Describe the bug**
Installing sparse with python 3.9.1 is no longer possible due to [numba llvmlite dependency issue](https://github.com/numba/numba/issues/6345)

**To Reproduce**
`pip install sparse`

**Expected behavior**
Sparse to install and build.

**System**
 - Arch Linux
 - python version 3.9.1

**Additional context**
Error raised:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting sparse
  Using cached sparse-0.11.2-py2.py3-none-any.whl (73 kB)
Requirement already satisfied: scipy>=0.19 in /home/jack/.local/lib/python3.9/site-packages (from sparse) (1.5.4)
Requirement already satisfied: numpy in /home/jack/.local/lib/python3.9/site-packages (from sparse) (1.19.4)
Collecting numba>=0.49
  Using cached numba-0.51.2-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from numba>=0.49->sparse) (51.1.2)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-njvhsfdc
       cwd: /tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.9/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, sparse
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ssboxxju/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jack/.local/include/python3.9/llvmlite
         cwd: /tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m12x4el1/llvmlite_fcb74e185a174cfc93db2ea3c84c2678/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ssboxxju/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jack/.local/include/python3.9/llvmlite Check the logs for full command output.

```

**Comment by hameerabbasi** [comment]
I believe there is ongoing work to bring Numba/llvmlite to Python 3.9, but some deep bytecode/behavioural changes are making that hard.

**Comment by hameerabbasi** [comment]
xref numba/numba#6345, numba/llvmlite#669

**Comment by hameerabbasi** [comment]
Oh, it's already in, which means it should be in the next release.

**Comment by stuartarchibald** [comment]
> I believe there is ongoing work to bring Numba/llvmlite to Python 3.9, but some deep bytecode/behavioural changes are making that hard.

A sample of the details of things that changed is [here](https://github.com/numba/numba/issues/6345#issuecomment-738696458). Work on 3.9 support in Numba is now complete, see [here](https://github.com/numba/numba/issues/6345#issuecomment-759509837) for how to get a development version that works on 3.9, a release candidate for Numba 0.53 should be tagged in a few weeks time. Hope this helps.

**Comment by JackWetherell** [comment]
Thank you for the information. Once this is released i'll close the issue.

**Comment by JackWetherell** [comment]
Sparse now installs for python 3.9 if the exact following versions are used as a dependency:
`numba==0.53.0rc1.post1`. But a regular `pip install sparse` does not work unless `numba==0.53.0rc1.post1` is already installed.

**Comment by JackWetherell** [comment]
I will leave a comment here and close once the final numba/llvmlite release is published, and  this workaround is no longer needed.

**Comment by JackWetherell** [comment]
The numba/llvmlite release is published. The above workaround is no longer needed. sparse now installs with python 3.9.1. 
The current versions of the relevant dependencies are:
```
sparse==0.11.2
numba==0.53.0
llvmlite==0.36.0
```
