### ISSUE TITLE
Scalar multiplication does not work with `GCXS`

### ISSUE THREAD

**Issue by sayandip18** [pydata/sparse#528]
**Describe the bug**
`GCXS` arrays cannot be multiplied with any scalar value.

**To Reproduce**
```python
>>> import sparse; import numpy as np
>>> s1=sparse.random((), format='gcxs')
>>> s2=np.random.rand()
>>> s1*s2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sayandip/anaconda3/lib/python3.8/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/home/sayandip/sparse/sparse/_sparse_array.py", line 305, in __array_ufunc__
    result = elemwise(ufunc, *inputs, **kwargs)
  File "/home/sayandip/sparse/sparse/_umath.py", line 49, in elemwise
    return _Elemwise(func, *args, **kwargs).get_result()
  File "/home/sayandip/sparse/sparse/_umath.py", line 446, in __init__
    processed_args.append(COO(arg))
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 221, in __init__
    arr = as_coo(
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 1492, in as_coo
    return x.asformat("coo")
  File "/home/sayandip/sparse/sparse/_compressed/compressed.py", line 524, in asformat
    ret = self.tocoo()
  File "/home/sayandip/sparse/sparse/_compressed/compressed.py", line 409, in tocoo
    return COO(
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 296, in __init__
    self._sort_indices()
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 1244, in _sort_indices
    linear = self.linear_loc()
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 940, in linear_loc
    return linear_loc(self.coords, self.shape)
  File "/home/sayandip/sparse/sparse/_coo/common.py", line 65, in linear_loc
    return np.ravel_multi_index(coords, shape)
  File "<__array_function__ internals>", line 5, in ravel_multi_index
ValueError: parameter multi_index must be a sequence of length 0
>>> s1.todense()*s2
0.0
```

**Expected behavior**
```python
>>> import sparse; import numpy as np
>>> s1=sparse.random((), format=sparse.GCXS)
>>> s2=np.random.rand()
>>> s1*s2
0.0
```

**System**
 - OS and version: Ubuntu 20.04.1
 - `sparse` version: `master`
 - NumPy version: 1.20.1

**Comment by Miheergautam** [comment]
import sparse
import numpy as np
s1 = sparse.random((), format='gcxs')
s2 = np.random.rand()
result = s1.todense() * s2
print(result)

**Comment by mtsokol** [comment]
Hi @sayandip18,
With the latest `sparse` version published on pypi (`0.15.1`) I couldn't reproduce this issue. Here's a google colab with your example executing succesfully:
https://colab.research.google.com/drive/1tDkhUPyYNRQE0noqmCEQMs_-LuTFcX8g
Can you try with e.g. `sparse` `0.15.1` and `numpy` `1.23.5`?
(FYI the default branch in `pydata/sparse` repo got renamed to `main` so you might be running an old version).

**Comment by sayandip18** [comment]
Hello @mtsokol, just tried reproducing this in my system. This is now working as expected. I came across this bug quite way back, so this possibly got fixed some time down the line. Should we close the issue?

**Comment by hameerabbasi** [comment]
Thanks for confirming, @sayandip18.
