### ISSUE TITLE
Bug: failing to install pydata/sparse with poetry

### ISSUE THREAD

**Issue by willow-ahrens** [pydata/sparse#794]
### sparse version checks

- [X] I checked that this issue has not been reported before [list of issues](https://github.com/pydata/sparse/issues).

- [X] I have confirmed this bug exists on the latest version of sparse.

- [X] I have confirmed this bug exists on the main branch of sparse.

### Describe the bug

poetry install results

### Steps or code to reproduce the bug

make a blank poetry project.

```
poetry add sparse
```

### Expected results

installs sparse

### Actual results

```
Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 5 updates, 0 removals

  - Downgrading llvmlite (0.42.0 -> 0.34.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  /private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpyvhdws4b/.venv/bin/python /private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpc55srz27/llvmlite-0.34.0/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpc55srz27/llvmlite-0.34.0/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpc55srz27/llvmlite-0.34.0/ffi/build.py", line 191, in <module>
      main()
    File "/private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpc55srz27/llvmlite-0.34.0/ffi/build.py", line 185, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpc55srz27/llvmlite-0.34.0/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/private/var/folders/3j/06rp16v14vv9v1ylqc38k5100000gn/T/tmpyvhdws4b/.venv/bin/python' failed with exit code 1
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with llvmlite (0.34.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "llvmlite (==0.34.0)"'.
```

### Please describe your system.

macos, Python 3.12.7

### Relevant log output

```shell
I think you need to bump the version of numba. I was able to fix by adding a dep on numba 0.60. llvmlite 0.34 is somewhat out of date.
```

**Comment by omdowley** [comment]
I ran into what seems to me to be the same underlying issue when trying to add sparse to a python 3.12.7 project via uv --  the most relevant line being

```
  × Failed to build `llvmlite==0.36.0`
```

Which does track, llvmlite 0.36.0 supports python <3.10. Tracking it back through the graph, this version of llvmlite was forced by numba 0.53.1, which was forced by a conflict between newer numba versions and numpy, which I ultimately worked out was actually being caused by an overly restrictive requirement on my numpy version -- uv had defaulted to the restriction `numpy>=2.2.4`. Relaxing this restriction to `numpy>=2.0.0` resolved the issue (turns out numpy 2.1.3 was what the dependency graph needed to resolve successfully).

**Comment by hameerabbasi** [comment]
Seems indeed like this is a bug in the poetry/uv dependency solver. However, numba 0.61 is on PyPI as of the time of writing; so we should be okay on closing this.
